# This is a basic workflow to help you get started with Actions
name: Create Issue Branch

on:
  issues:
    mode: chatops
    branchName: '${issue.number}-${issue.title,}'
    gitSafeReplacementChar: '-'
    branches:
      - label: enhancement
        prefix: feature/${issue.user.login}/
      - label: bug
        prefix: bugfix/${issue.user.login}/
  issue_comment:
    commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
    
jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
