# This is a basic workflow to help you get started with Actions

name: Create Issue Branch

on:
  issues:
    branches:
      - label: enhancement
        prefix: feature/${issue.user.login}/
        gitSafeReplacementChar: '-'
        branchName: '${issue.number}-${issue.title,}'
        commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
      - label: bug
        prefix: bugfix/${issue.user.login}/
        gitSafeReplacementChar: '-'
        branchName: '${issue.number}-${issue.title,}'
        commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
    mode: chatops
jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
